from pydantic import BaseModel, Field
from typing import Literal, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .effect_types import EffectSuggestion


class AnimationFrame(BaseModel):
    """Single frame in an animation script."""
    
    frame_index: int = Field(
        ge=0,
        description="Zero-indexed frame position"
    )
    phase: Literal["Anticipation", "Contact", "Recovery", "Idle", "Follow-through", "Startup"] = Field(
        description="Animation phase for this frame"
    )
    pose_description: str = Field(
        description="Detailed description of the character pose"
    )
    visual_focus: str = Field(
        description="Key visual element to emphasize in this frame"
    )
    impact_window: bool = Field(
        default=False,
        description="Whether this frame is an impact/hit detection window"
    )
    force_vector: Optional[str] = Field(
        default=None,
        description="Direction and intensity of force (e.g., 'forward-down', 'up-strong')"
    )


class AnimationScript(BaseModel):
    """
    Biomechanical animation script generated by Stage 5.
    Describes each frame in physics-grounded detail.
    """
    
    action_type: str = Field(
        description="Type of action being animated"
    )
    difficulty_tier: Literal["LIGHT", "HEAVY", "BOSS"] = Field(
        description="Difficulty tier affecting exaggeration"
    )
    physics_reasoning: str = Field(
        description="Explanation of physics/biomechanics considerations"
    )
    frames: list[AnimationFrame] = Field(
        description="Frame-by-frame animation breakdown"
    )
    suggested_effects: list[dict] = Field(
        default_factory=list,
        description="AI-suggested visual effects for this animation (optional)"
    )
    
    @property
    def frame_count(self) -> int:
        """Total number of frames in this script."""
        return len(self.frames)


class FrameBudget(BaseModel):
    """Result of frame budget computation (Stage 3c)."""
    
    action_type: str
    difficulty_tier: Literal["LIGHT", "HEAVY", "BOSS"]
    weapon_mass: Literal["none", "light", "medium", "heavy", "oversized"]
    perspective: Literal["side", "front", "isometric", "top_down"]
    base_frames: int
    multiplier_applied: float
    final_frame_count: int = Field(ge=4, le=16)
    grid_dim: Literal[2, 3, 4] = Field(
        description="Grid dimension for spritesheet (2x2, 3x3, or 4x4)"
    )
    justification: str = Field(
        description="Reasoning for the final frame count"
    )
